### ISSUE TITLE
README first example gives: `Status 500 INTERNAL_SERVER_ERROR`

### ISSUE THREAD

**Issue by ramiromagno** [ramses-antibiotics/snomedizer#42]
I tried running the first example in the README but it gives an error:

```R
> api_concepts(term = "pneumonia", activeFilter = TRUE)
Response [https://snowstorm.test-nictiz.nl/MAIN/concepts?term=pneumonia&limit=50&offset=0&activeFilter=TRUE]
  Date: 2023-09-25 22:24
  Status: 500
  Content-Type: application/json
  Size: 230 B
{
  "error" : "INTERNAL_SERVER_ERROR",
  "message" : "Index [branch] not found.; nested exception is [branch] ElasticsearchStatusException[Elasticsearch exception [type=index_not_foun...
Warning message:
Status 500 INTERNAL_SERVER_ERROR
Index [branch] not found.; nested exception is [branch] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [branch]]] 
```

**Comment by peterdutey** [comment]
Hi Ramiro 
Thanks for reporting this.
Snomedizer depends on access to a Snowstorm terminology server. On launch, it looks for a know public server and on this occasion chose this particular one, which is no longer working as expected. Interesting that snomedizer's tests didn't fail on launch though.
To remove the dependence on Snowstorm, I need to redevelop snomedizer to use a different terminology service called [Hermes](https://github.com/wardle/hermes/). Until then, you might find it helpful to work with Hermes through its REST API.
Could this be a solution for you?
Best wishes
Peter

**Comment by ramiromagno** [comment]
Hi Peter,

Thank you for your quick answer.

When you say working through their REST API, do you mean running a local microservice with the REST API server, or is there a public service I can use? I mean, it was not obvious to me from Hermes' hefty README whether the author provides a public service like the Snowstorm terminology server.

What about your plans with Snomedizer and Hermes? Do you think it's possible in one simple installation of `{Snomedizer}`  to install and run Hermes too, or the user will always have to provide the Hermes service on its own, and then somehow point `{Snomedizer}` to use that Hermes' instance?

**Comment by peterdutey** [comment]
Hi Ramiro
Yes running a local microservice. Hermes is pretty easy to build on a typical laptop.
It does mean working with httr (or equivalent) and building REST queries from scratch.
Long term and when I can find the time to do it, yes snomedizer will probably include functions to facilitate the build with whatever SNOMED CT distro the user wants.
Bw
P

**Comment by ramiromagno** [comment]
Okay Peter! Thanks for the feedback.
